version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-personas
    environment:
      MYSQL_ROOT_PASSWORD: MySQL1234
      MYSQL_DATABASE: personas_db
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: backend-personas
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: MySQL1234
      DB_DATABASE: personas_db
    ports:
      - "3001:3001" # backend
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend-personas
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mysql_data: